spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: rhdqnWofktm2!
    driver-class-name: com.mysql.cj.jdbc.Driver
    show-sql: true
    defer-datasource-initialization: true

jwt:
  secret: kingIsBackKingIsBackKingIsBackKingIsBack
